logging:
  level:
    org.springframework.web: ERROR
    com.hendisantika.springboot.swagger: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
file: ./logs/application.log
spring:
  datasource:
    url: jdbc:mysql://localhost/swaggerDB?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect